CREATE TYPE GENDER AS ENUM (
    'male',
    'female'
);

CREATE TABLE IF NOT EXISTS AYAHS (
    id SERIAL PRIMARY KEY,
    ayah INT NOT NULL,
    surah INT NOT NULL,
    "page" INT NOT NULL,
    text TEXT NOT NULL,
    glyphs TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    country VARCHAR(255) NOT NULL,
    province VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    gender GENDER NOT NULL,
    proficiency_level VARCHAR(255) NOT NULL,
    studied_quran_before BOOLEAN NOT NULL,
    job_title VARCHAR(255) DEFAULT NULL,
    lisper VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
 
CREATE TABLE IF NOT EXISTS TASKS (
    id SERIAL PRIMARY KEY,
    ayah INT NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ayah) REFERENCES AYAHS(id) ON DELETE CASCADE
);
 
CREATE TABLE IF NOT EXISTS USER_TASKS (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    task_id INT NOT NULL,
    audio_url TEXT NOT NULL,
    audio_duration FLOAT NOT NULL DEFAULT 0,
    is_validated BOOLEAN NOT NULL DEFAULT FALSE,
    validated_by INT NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
    FOREIGN KEY (task_id) REFERENCES TASKS(id) ON DELETE CASCADE,
    FOREIGN KEY (validated_by) REFERENCES USERS(id) ON DELETE CASCADE
);
 