// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Gender string

const (
	GenderMale   Gender = "male"
	GenderFemale Gender = "female"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender `json:"gender"`
	Valid  bool   `json:"valid"` // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

type Ayah struct {
	ID     int32  `json:"id"`
	Ayah   int32  `json:"ayah"`
	Surah  int32  `json:"surah"`
	Page   int32  `json:"page"`
	Text   string `json:"text"`
	Glyphs string `json:"glyphs"`
}

type Task struct {
	ID        int32            `json:"id"`
	Ayah      int32            `json:"ayah"`
	IsDeleted pgtype.Bool      `json:"is_deleted"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID                 int32            `json:"id"`
	Name               string           `json:"name"`
	Email              string           `json:"email"`
	Country            string           `json:"country"`
	Province           string           `json:"province"`
	Age                int32            `json:"age"`
	Gender             Gender           `json:"gender"`
	ProficiencyLevel   string           `json:"proficiency_level"`
	StudiedQuranBefore bool             `json:"studied_quran_before"`
	JobTitle           pgtype.Text      `json:"job_title"`
	Lisper             pgtype.Text      `json:"lisper"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type UserTask struct {
	ID            int32            `json:"id"`
	UserID        int32            `json:"user_id"`
	TaskID        int32            `json:"task_id"`
	AudioUrl      string           `json:"audio_url"`
	AudioDuration float64          `json:"audio_duration"`
	IsValidated   bool             `json:"is_validated"`
	ValidatedBy   pgtype.Int4      `json:"validated_by"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}
